package org.terraframe

//TODO items, ui_items, id
sealed abstract class UiItem(val imageName: String, val name: String, val id: Short)
object EmptyUiItem                extends UiItem("air", "Air", 0)
object DirtUiItem                 extends UiItem("blocks/dirt", "Dirt", 1)
object StoneUiItem                extends UiItem("blocks/stone", "Stone", 2)
object CopperOreUiItem            extends UiItem("ores/copper_ore", "Copper Ore", 3)
object IronOreUiItem              extends UiItem("ores/iron_ore", "Iron Ore", 4)
object SilverOreUiItem            extends UiItem("ores/silver_ore", "Silver Ore", 5)
object GoldOreUiItem              extends UiItem("ores/gold_ore", "Gold Ore", 6)
object CopperPickUiItem           extends UiItem("tools/copper_pick", "Copper Pick", 7)
object IronPickUiItem             extends UiItem("tools/iron_pick", "Iron Pick", 8)
object SilverPickUiItem           extends UiItem("tools/silver_pick", "Silver Pick", 9)
object GoldPickUiItem             extends UiItem("tools/gold_pick", "Gold Pick", 10)
object CopperAxeUiItem            extends UiItem("tools/copper_axe", "Copper Axe", 11)
object IronAxeUiItem              extends UiItem("tools/iron_axe", "Iron Axe", 12)
object SilverAxeUiItem            extends UiItem("tools/silver_axe", "Silver Axe", 13)
object GoldAxeUiItem              extends UiItem("tools/gold_axe", "Gold Axe", 14)
object WoodUiItem                 extends UiItem("blocks/wood", "Wood", 15)
object CopperSwordUiItem          extends UiItem("tools/copper_sword", "Copper Sword", 16)
object IronSwordUiItem            extends UiItem("tools/iron_sword", "Iron Sword", 17)
object SilverSwordUiItem          extends UiItem("tools/silver_sword", "Silver Sword", 18)
object GoldSwordUiItem            extends UiItem("tools/gold_sword", "Gold Sword", 19)
object WorkbenchUiItem            extends UiItem("machines/workbench", "Workbench", 20)
object WoodenChestUiItem          extends UiItem("machines/wooden_chest", "Wooden Chest", 21)
object StoneChestUiItem           extends UiItem("machines/stone_chest", "Stone Chest", 22)
object CopperChestUiItem          extends UiItem("machines/copper_chest", "Copper Chest", 23)
object IronChestUiItem            extends UiItem("machines/iron_chest", "Iron Chest", 24)
object SilverChestUiItem          extends UiItem("machines/silver_chest", "Silver Chest", 25)
object GoldChestUiItem            extends UiItem("machines/gold_chest", "Gold Chest", 26)
object FurnaceUiItem              extends UiItem("machines/furnace", "Furnace", 27)
object CoalUiItem                 extends UiItem("ores/coal", "Coal", 28)
object CopperIngotUiItem          extends UiItem("ingots/copper_ingot", "Copper Ingot", 29)
object IronIngotUiItem            extends UiItem("ingots/iron_ingot", "Iron Ingot", 30)
object SilverIngotUiItem          extends UiItem("ingots/silver_ingot", "Silver Ingot", 31)
object GoldIngotUiItem            extends UiItem("ingots/gold_ingot", "Gold Ingot", 32)
object StoneLighterUiItem         extends UiItem("tools/stone_lighter", "Stone Lighter", 33)
object LumenstoneUiItem           extends UiItem("ores/lumenstone", "Lumenstone", 34)
object WoodenTorchUiItem          extends UiItem("torches/wooden_torch", "Wooden Torch", 35)
object CoalTorchUiItem            extends UiItem("torches/coal_torch", "Coal Torch", 36)
object LumenstoneTorchUiItem      extends UiItem("torches/lumenstone_torch", "Lumenstone Torch", 37)
object ZincOreUiItem              extends UiItem("ores/zinc_ore", "Zinc Ore", 38)
object RhymestoneOreUiItem        extends UiItem("ores/rhymestone_ore", "Rhymestone Ore", 39)
object ObduriteOreUiItem          extends UiItem("ores/obdurite_ore", "Obdurite Ore", 40)
object AluminumOreUiItem          extends UiItem("ores/aluminum_ore", "Aluminum Ore", 41)
object LeadOreUiItem              extends UiItem("ores/lead_ore", "Lead Ore", 42)
object UraniumOreUiItem           extends UiItem("ores/uranium_ore", "Uranium Ore", 43)
object ZythiumOreUiItem           extends UiItem("ores/zythium_ore", "Zythium Ore", 44)
object SiliconOreUiItem           extends UiItem("ores/silicon_ore", "Silicon Ore", 45)
object IrradiumOreUiItem          extends UiItem("ores/irradium_ore", "Irradium Ore", 46)
object NullstoneUiItem            extends UiItem("ores/nullstone", "Nullstone", 47)
object MeltstoneUiItem            extends UiItem("ores/meltstone", "Meltstone", 48)
object SkystoneUiItem             extends UiItem("ores/skystone", "Skystone", 49)
object MagnetiteOreUiItem         extends UiItem("ores/magnetite_ore", "Magnetite Ore", 50)
object ZincPickUiItem             extends UiItem("tools/zinc_pick", "Zinc Pick", 51)
object ZincAxeUiItem              extends UiItem("tools/zinc_axe", "Zinc Axe", 52)
object ZincSwordUiItem            extends UiItem("tools/zinc_sword", "Zinc Sword", 53)
object RhymestonePickUiItem       extends UiItem("tools/rhymestone_pick", "Rhymestone Pick", 54)
object RhymestoneAxeUiItem        extends UiItem("tools/rhymestone_axe", "Rhymestone Axe", 55)
object RhymestoneSwordUiItem      extends UiItem("tools/rhymestone_sword", "Rhymestone Sword", 56)
object ObduritePickUiItem         extends UiItem("tools/obdurite_pick", "Obdurite Pick", 57)
object ObduriteAxeUiItem          extends UiItem("tools/obdurite_axe", "Obdurite Axe", 58)
object ObduriteSwordUiItem        extends UiItem("tools/obdurite_sword", "Obdurite Sword", 59)
object ZincIngotUiItem            extends UiItem("ingots/zinc_ingot", "Zinc Ingot", 60)
object RhymestoneIngotUiItem      extends UiItem("ingots/rhymestone_ingot", "Rhymestone Ingot", 61)
object ObduriteIngotUiItem        extends UiItem("ingots/obdurite_ingot", "Obdurite Ingot", 62)
object AluminumIngotUiItem        extends UiItem("ingots/aluminum_ingot", "Aluminum Ingot", 63)
object LeadIngotUiItem            extends UiItem("ingots/lead_ingot", "Lead Ingot", 64)
object UraniumBarUiItem           extends UiItem("ingots/uranium_bar", "Uranium Bar", 65)
object RefinedUraniumUiItem       extends UiItem("ingots/refined_uranium", "Refined Uranium", 66)
object ZythiumBarUiItem           extends UiItem("ingots/zythium_bar", "Zythium Bar", 67)
object SiliconBarUiItem           extends UiItem("ingots/silicon_bar", "Silicon Bar", 68)
object IrradiumIngotUiItem        extends UiItem("ingots/irradium_ingot", "Irradium Ingot", 69)
object NullstoneBarUiItem         extends UiItem("ingots/nullstone_bar", "Nullstone Bar", 70)
object MeltstoneBarUiItem         extends UiItem("ingots/meltstone_bar", "Meltstone Bar", 71)
object SkystoneBarUiItem          extends UiItem("ingots/skystone_bar", "Skystone Bar", 72)
object MagnetiteIngotUiItem       extends UiItem("ingots/magnetite_ingot", "Magnetite Ingot", 73)
object SandUiItem                 extends UiItem("blocks/sand", "Sand", 74)
object SnowUiItem                 extends UiItem("blocks/snow", "Snow", 75)
object GlassUiItem                extends UiItem("blocks/glass", "Glass", 76)
object SunflowerSeedsUiItem       extends UiItem("seeds/sunflower_seeds", "Sunflower Seeds", 77)
object SunflowerUiItem            extends UiItem("herbs/sunflower", "Sunflower", 78)
object MoonflowerSeedsUiItem      extends UiItem("seeds/moonflower_seeds", "Moonflower Seeds", 79)
object MoonflowerUiItem           extends UiItem("herbs/moonflower", "Moonflower", 80)
object DryweedSeedsUiItem         extends UiItem("seeds/dryweed_seeds", "Dryweed Seeds", 81)
object DryweedUiItem              extends UiItem("herbs/dryweed", "Dryweed", 82)
object GreenleafSeedsUiItem       extends UiItem("seeds/greenleaf_seeds", "Greenleaf Seeds", 83)
object GreenleafUiItem            extends UiItem("herbs/greenleaf", "Greenleaf", 84)
object FrostleafSeedsUiItem       extends UiItem("seeds/frostleaf_seeds", "Frostleaf Seeds", 85)
object FrostleafUiItem            extends UiItem("herbs/frostleaf", "Frostleaf", 86)
object CaverootSeedsUiItem        extends UiItem("seeds/caveroot_seeds", "Caveroot Seeds", 87)
object CaverootUiItem             extends UiItem("herbs/caveroot", "Caveroot", 88)
object SkyblossomSeedsUiItem      extends UiItem("seeds/skyblossom_seeds", "Skyblossom Seeds", 89)
object SkyblossomUiItem           extends UiItem("herbs/skyblossom", "Skyblossom", 90)
object VoidRotSeedsUiItem         extends UiItem("seeds/void_rot_seeds", "Void Rot Seeds", 91)
object VoidRotUiItem              extends UiItem("herbs/void_rot", "Void Rot", 92)
object MudUiItem                  extends UiItem("blocks/mud", "Mud", 93)
object SandstoneUiItem            extends UiItem("blocks/sandstone", "Sandstone", 94)
object MarshleafSeedsUiItem       extends UiItem("seeds/marshleaf_seeds", "Marshleaf Seeds", 95)
object MarshleafUiItem            extends UiItem("herbs/marshleaf", "Marshleaf", 96)
object BlueGooUiItem              extends UiItem("goo/blue_goo", "Blue Goo", 97)
object GreenGooUiItem             extends UiItem("goo/green_goo", "Green Goo", 98)
object RedGooUiItem               extends UiItem("goo/red_goo", "Red Goo", 99)
object YellowGooUiItem            extends UiItem("goo/yellow_goo", "Yellow Goo", 100)
object BlackGooUiItem             extends UiItem("goo/black_goo", "Black Goo", 101)
object WhiteGooUiItem             extends UiItem("goo/white_goo", "White Goo", 102)
object AstralShardUiItem          extends UiItem("goo/astral_shard", "Astral Shard", 103)
object RottenChunkUiItem          extends UiItem("goo/rotten_chunk", "Rotten Chunk", 104)
object CopperHelmetUiItem         extends UiItem("armor/copper_helmet", "Copper Helmet", 105)
object CopperChestplateUiItem     extends UiItem("armor/copper_chestplate", "Copper Chestplate", 106)
object CopperLeggingsUiItem       extends UiItem("armor/copper_leggings", "Copper Leggings", 107)
object CopperGreavesUiItem        extends UiItem("armor/copper_greaves", "Copper Greaves", 108)
object IronHelmetUiItem           extends UiItem("armor/iron_helmet", "Iron Helmet", 109)
object IronChestplateUiItem       extends UiItem("armor/iron_chestplate", "Iron Chestplate", 110)
object IronLeggingsUiItem         extends UiItem("armor/iron_leggings", "Iron Leggings", 111)
object IronGreavesUiItem          extends UiItem("armor/iron_greaves", "Iron Greaves", 112)
object SilverHelmetUiItem         extends UiItem("armor/silver_helmet", "Silver Helmet", 113)
object SilverChestplateUiItem     extends UiItem("armor/silver_chestplate", "Silver Chestplate", 114)
object SilverLeggingsUiItem       extends UiItem("armor/silver_leggings", "Silver Leggings", 115)
object SilverGreavesUiItem        extends UiItem("armor/silver_greaves", "Silver Greaves", 116)
object GoldHelmetUiItem           extends UiItem("armor/gold_helmet", "Gold Helmet", 117)
object GoldChestplateUiItem       extends UiItem("armor/gold_chestplate", "Gold Chestplate", 118)
object GoldLeggingsUiItem         extends UiItem("armor/gold_leggings", "Gold Leggings", 119)
object GoldGreavesUiItem          extends UiItem("armor/gold_greaves", "Gold Greaves", 120)
object ZincHelmetUiItem           extends UiItem("armor/zinc_helmet", "Zinc Helmet", 121)
object ZincChestplateUiItem       extends UiItem("armor/zinc_chestplate", "Zinc Chestplate", 122)
object ZincLeggingsUiItem         extends UiItem("armor/zinc_leggings", "Zinc Leggings", 123)
object ZincGreavesUiItem          extends UiItem("armor/zinc_greaves", "Zinc Greaves", 124)
object RhymestoneHelmetUiItem     extends UiItem("armor/rhymestone_helmet", "Rhymestone Helmet", 125)
object RhymestoneChestplateUiItem extends UiItem("armor/rhymestone_chestplate", "Rhymestone Chestplate", 126)
object RhymestoneLeggingsUiItem   extends UiItem("armor/rhymestone_leggings", "Rhymestone Leggings", 127)
object RhymestoneGreavesUiItem    extends UiItem("armor/rhymestone_greaves", "Rhymestone Greaves", 128)
object ObduriteHelmetUiItem       extends UiItem("armor/obdurite_helmet", "Obdurite Helmet", 129)
object ObduriteChestplateUiItem   extends UiItem("armor/obdurite_chestplate", "Obdurite Chestplate", 130)
object ObduriteLeggingsUiItem     extends UiItem("armor/obdurite_leggings", "Obdurite Leggings", 131)
object ObduriteGreavesUiItem      extends UiItem("armor/obdurite_greaves", "Obdurite Greaves", 132)
object AluminumHelmetUiItem       extends UiItem("armor/aluminum_helmet", "Aluminum Helmet", 133)
object AluminumChestplateUiItem   extends UiItem("armor/aluminum_chestplate", "Aluminum Chestplate", 134)
object AluminumLeggingsUiItem     extends UiItem("armor/aluminum_leggings", "Aluminum Leggings", 135)
object AluminumGreavesUiItem      extends UiItem("armor/aluminum_greaves", "Aluminum Greaves", 136)
object LeadHelmetUiItem           extends UiItem("armor/lead_helmet", "Lead Helmet", 137)
object LeadChestplateUiItem       extends UiItem("armor/lead_chestplate", "Lead Chestplate", 138)
object LeadLeggingsUiItem         extends UiItem("armor/lead_leggings", "Lead Leggings", 139)
object LeadGreavesUiItem          extends UiItem("armor/lead_greaves", "Lead Greaves", 140)
object ZythiumHelmetUiItem        extends UiItem("armor/zythium_helmet", "Zythium Helmet", 141)
object ZythiumChestplateUiItem    extends UiItem("armor/zythium_chestplate", "Zythium Chestplate", 142)
object ZythiumLeggingsUiItem      extends UiItem("armor/zythium_leggings", "Zythium Leggings", 143)
object ZythiumGreavesUiItem       extends UiItem("armor/zythium_greaves", "Zythium Greaves", 144)
object AluminumPickUiItem         extends UiItem("tools/aluminum_pick", "Aluminum Pick", 145)
object AluminumAxeUiItem          extends UiItem("tools/aluminum_axe", "Aluminum Axe", 146)
object AluminumSwordUiItem        extends UiItem("tools/aluminum_sword", "Aluminum Sword", 147)
object LeadPickUiItem             extends UiItem("tools/lead_pick", "Lead Pick", 148)
object LeadAxeUiItem              extends UiItem("tools/lead_axe", "Lead Axe", 149)
object LeadSwordUiItem            extends UiItem("tools/lead_sword", "Lead Sword", 150)
object ZincChestUiItem            extends UiItem("machines/zinc_chest", "Zinc Chest", 151)
object RhymestoneChestUiItem      extends UiItem("machines/rhymestone_chest", "Rhymestone Chest", 152)
object ObduriteChestUiItem        extends UiItem("machines/obdurite_chest", "Obdurite Chest", 153)
object WoodenPickUiItem           extends UiItem("tools/wooden_pick", "Wooden Pick", 154)
object WoodenAxeUiItem            extends UiItem("tools/wooden_axe", "Wooden Axe", 155)
object WoodenSwordUiItem          extends UiItem("tools/wooden_sword", "Wooden Sword", 156)
object StonePickUiItem            extends UiItem("tools/stone_pick", "Stone Pick", 157)
object StoneAxeUiItem             extends UiItem("tools/stone_axe", "Stone Axe", 158)
object StoneSwordUiItem           extends UiItem("tools/stone_sword", "Stone Sword", 159)
object BarkUiItem                 extends UiItem("goo/bark", "Bark", 160)
object CobblestoneUiItem          extends UiItem("blocks/cobblestone", "Cobblestone", 161)
object ChiseledStoneUiItem        extends UiItem("blocks/chiseled_stone", "Chiseled Stone", 162)
object ChiseledCobblestoneUiItem  extends UiItem("blocks/chiseled_cobblestone", "Chiseled Cobblestone", 163)
object StoneBricksUiItem          extends UiItem("blocks/stone_bricks", "Stone Bricks", 164)
object ClayUiItem                 extends UiItem("blocks/clay", "Clay", 165)
object ClayBricksUiItem           extends UiItem("blocks/clay_bricks", "Clay Bricks", 166)
object VarnishUiItem              extends UiItem("potions/varnish", "Varnish", 167)
object VarnishedWoodUiItem        extends UiItem("blocks/varnished_wood", "Varnished Wood", 168)
object MagnetitePickUiItem        extends UiItem("tools/magnetite_pick", "Magnetite Pick", 169)
object MagnetiteAxeUiItem         extends UiItem("tools/magnetite_axe", "Magnetite Axe", 170)
object MagnetiteSwordUiItem       extends UiItem("tools/magnetite_sword", "Magnetite Sword", 171)
object IrradiumPickUiItem         extends UiItem("tools/irradium_pick", "Irradium Pick", 172)
object IrradiumAxeUiItem          extends UiItem("tools/irradium_axe", "Irradium Axe", 173)
object IrradiumSwordUiItem        extends UiItem("tools/irradium_sword", "Irradium Sword", 174)
object ZythiumWireUiItem          extends UiItem("wires/zythium_wire", "Zythium Wire", 175)
object ZythiumTorchUiItem         extends UiItem("torches/zythium_torch", "Zythium Torch", 176)
object ZythiumLampUiItem          extends UiItem("blocks/zythium_lamp", "Zythium Lamp", 177)
object LeverUiItem                extends UiItem("misc/lever", "Lever", 178)
object CharcoalUiItem             extends UiItem("dust/charcoal", "Charcoal", 179)
object ZythiumAmplifierUiItem     extends UiItem("wires/zythium_amplifier", "Zythium Amplifier", 180)
object ZythiumInverterUiItem      extends UiItem("wires/zythium_inverter", "Zythium Inverter", 181)
object ButtonUiItem               extends UiItem("misc/button", "Button", 182)
object WoodenPressurePlateUiItem  extends UiItem("misc/wooden_pressure_plate", "Wooden Pressure Plate", 183)
object StonePressurePlateUiItem   extends UiItem("misc/stone_pressure_plate", "Stone Pressure Plate", 184)
object ZythiumPressurePlateUiItem extends UiItem("misc/zythium_pressure_plate", "Zythium Pressure Plate", 185)
object ZythiumDelayer1UiItem      extends UiItem("wires/zythium_delayer_1", "Zythium Delayer", 186)
object ZythiumDelayer2UiItem      extends UiItem("wires/zythium_delayer_2", "Zythium Delayer", 187)
object ZythiumDelayer4UiItem      extends UiItem("wires/zythium_delayer_4", "Zythium Delayer", 188)
object ZythiumDelayer8UiItem      extends UiItem("wires/zythium_delayer_8", "Zythium Delayer", 189)
object WrenchUiItem               extends UiItem("tools/wrench", "Wrench", 190)
